### ISSUE TITLE
Runtime error in "Memories, reappear"

### ISSUE THREAD

**Issue by someNesa** [Syyrion/pack_anniversary#5]
Runtime error when starting the level:
[runLuaFunctionIfExists] Runtime error on "onLoad" with level "Memories, reappear":
[string "chunk"]:93: attempt to index local 'input' (a nil value)

**Comment by Syyrion** [comment]
He's still got some stuff to work on. It likely has something to do with an invalid file path since he's using `io.read`. I've already notified him.

**Comment by C-Viridian-19053** [comment]
most likely it was a different location or smth...

**Comment by C-Viridian-19053** [comment]
alright, i'll fix that soon

**Comment by C-Viridian-19053** [comment]
fix done.

**Comment by C-Viridian-19053** [comment]
+ added my new branch.
